/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.userController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import sombra.textoSombra;

/**
 *
 * @author gameV
 */
public class Registro extends javax.swing.JFrame {

    public Registro() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);

        textoSombra correo = new textoSombra("Correo", inputCorreo);
        setResizable(true);
        textoSombra nombre = new textoSombra("Nombre", inputNombre);
        setResizable(true);

        textoSombra id = new textoSombra("Identificacion", inputIdentificacion);
        setResizable(true);

        textoSombra apellido = new textoSombra("Apellido", inputApellido);
        setResizable(true);

        textoSombra user = new textoSombra("User", inputUsuario);
        setResizable(true);

        textoSombra contraseña = new textoSombra("Contraseña", inputContraseña);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUnete = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JLabel();
        inputContraseña = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputCorreo = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        inputApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        inputIdentificacion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();
        inputNombre = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();
        returnImage = new javax.swing.JLabel();
        returnBottom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUnete.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        txtUnete.setForeground(new java.awt.Color(0, 0, 0));
        txtUnete.setText("Unete a la familia voltrix");
        jPanel1.add(txtUnete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 290, -1));

        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Ingrese su correo electronico");
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 20));

        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Ingrese su user");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 320, 20));

        inputUsuario.setBackground(new java.awt.Color(0, 0, 0, 0));
        inputUsuario.setForeground(new java.awt.Color(51, 51, 51));
        inputUsuario.setBorder(null);
        inputUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(inputUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 290, 30));

        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.setText("Ingrese su contraseña");
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 320, 20));

        inputContraseña.setBackground(new java.awt.Color(0, 0, 0, 0
        ));
        inputContraseña.setForeground(new java.awt.Color(0, 0, 0));
        inputContraseña.setBorder(null);
        jPanel1.add(inputContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 290, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image 3 (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 490, 380));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Voltrix car's");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 348, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Calidad e innovacion en cada kilometro");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 348, 27));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image 5.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 660, 550));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 320, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 320, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen de WhatsApp 2024-09-19 a las 14.46.04_8cb85dea.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen de WhatsApp 2024-09-19 a las 14.48.05_f14395a5.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, 30));

        inputCorreo.setBackground(new java.awt.Color(0, 0, 0, 0));
        inputCorreo.setForeground(new java.awt.Color(51, 51, 51));
        inputCorreo.setBorder(null);
        inputCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorreoActionPerformed(evt);
            }
        });
        inputCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 290, 30));

        txtNombre1.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre1.setText("Ingrese su nombre");
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 320, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 320, 10));

        inputApellido.setBackground(new java.awt.Color(0, 0, 0, 0));
        inputApellido.setForeground(new java.awt.Color(51, 51, 51));
        inputApellido.setBorder(null);
        inputApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputApellidoActionPerformed(evt);
            }
        });
        inputApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(inputApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 290, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profile-user.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen de WhatsApp 2024-09-19 a las 14.48.05_f14395a5.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 40, 30));

        txtNombre2.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre2.setText("Ingrese su apellido");
        jPanel1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 320, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 320, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 320, 10));

        inputIdentificacion.setBackground(new java.awt.Color(0, 0, 0, 0));
        inputIdentificacion.setForeground(new java.awt.Color(51, 51, 51));
        inputIdentificacion.setBorder(null);
        inputIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdentificacionActionPerformed(evt);
            }
        });
        inputIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(inputIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 320, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/id-card (1).png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 40, 30));

        txtNombre3.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre3.setText("Ingrese su identificacion");
        jPanel1.add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 320, 20));

        Registrarse.setBackground(new java.awt.Color(0, 0, 0));
        Registrarse.setText("Registarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 130, 30));

        inputNombre.setBackground(new java.awt.Color(0, 0, 0, 0));
        inputNombre.setForeground(new java.awt.Color(51, 51, 51));
        inputNombre.setBorder(null);
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        inputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNombreKeyTyped(evt);
            }
        });
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 290, 30));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 30, 30));

        hidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hide (1).png"))); // NOI18N
        hidden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hiddenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hiddenMouseReleased(evt);
            }
        });
        jPanel1.add(hidden, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, 50));

        returnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-return-28.png"))); // NOI18N
        jPanel1.add(returnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 40));

        returnBottom.setBackground(new java.awt.Color(0, 0, 0));
        returnBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBottomActionPerformed(evt);
            }
        });
        jPanel1.add(returnBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuarioActionPerformed

    }//GEN-LAST:event_inputUsuarioActionPerformed

    private void inputCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorreoActionPerformed

    }//GEN-LAST:event_inputCorreoActionPerformed

    private void inputApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputApellidoActionPerformed

    private void inputIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdentificacionActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed

        String[] groserias = {"hijueputa", "hijodeputa", "hijo de puta", "malparido", "desgraciado", "mongolico", "gonorrea", "paraco", "hpta", "hp", "mlp", "perra", "sorra", "zorra", "degenerada", "mierda", "mrd", "caca", "puta", "maldito"};
        String correo = inputCorreo.getText();
        String nombre = inputCorreo.getText();
        String apellido = inputApellido.getText();
        String identificacion = inputIdentificacion.getText();
        String user = inputUsuario.getText();
        String contraseña = new String(inputContraseña.getPassword());

        userController controlador = new userController();

        if (correo.isEmpty() || nombre.isEmpty() || apellido.isEmpty()
                || identificacion.isEmpty() || user.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombre.length() > 0 && nombre.chars().distinct().count() == 1 || apellido.length() > 0 && apellido.chars().distinct().count() == 1) {
            JOptionPane.showMessageDialog(this, "El nombre y/o apellido no puede contener el mismo carácter repetido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (String groseria : groserias) {
            if (nombre.toLowerCase().contains(groseria)
                    || apellido.toLowerCase().contains(groseria)
                    || correo.toLowerCase().contains(groseria)) {
                JOptionPane.showMessageDialog(this, "Por favor, evite usar palabras inapropiadas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (!correo.contains("@") || !correo.endsWith(".com")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un email válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean registrado = controlador.registroUsuario(correo, nombre, apellido, identificacion, user, contraseña);

        if (registrado) {
            this.dispose();
            new InicioSesion().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el usuario. Inténtelo de nuevo.");
        }

    }//GEN-LAST:event_RegistrarseActionPerformed

    private void inputIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdentificacionKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo se permiten números en este campo.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_inputIdentificacionKeyTyped

    private void inputCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCorreoKeyTyped

    }//GEN-LAST:event_inputCorreoKeyTyped

    private void inputApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputApellidoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo se permiten letras en este campo.", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_inputApellidoKeyTyped

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo se permiten letras en este campo.", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_inputNombreKeyTyped

    private void hiddenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenMousePressed
        show.setVisible(true);
        hidden.setVisible(false);
        inputContraseña.setEchoChar((char) 0);
    }//GEN-LAST:event_hiddenMousePressed

    private void hiddenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiddenMouseReleased

    }//GEN-LAST:event_hiddenMouseReleased

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        show.setVisible(false);
        hidden.setVisible(true);
        inputContraseña.setEchoChar('*');
    }//GEN-LAST:event_showMouseClicked

    private void returnBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBottomActionPerformed

        this.dispose();
        new InicioSesion().setVisible(true);
    }//GEN-LAST:event_returnBottomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrarse;
    private javax.swing.JLabel hidden;
    private javax.swing.JTextField inputApellido;
    private javax.swing.JPasswordField inputContraseña;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputIdentificacion;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton returnBottom;
    private javax.swing.JLabel returnImage;
    private javax.swing.JLabel show;
    private javax.swing.JLabel txtContraseña;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNombre2;
    private javax.swing.JLabel txtNombre3;
    private javax.swing.JLabel txtUnete;
    // End of variables declaration//GEN-END:variables
}
